---
name: Update simdutf library

on:
  schedule:
    # At 12:10 on every day-of-month.
    - cron: '10 12 */1 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5
        name: Setup Go ${{ matrix.go-version }}
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check for updates
        run: python3 ./scripts/update-simdutf.py
        env:
          SIMDUTF_GH_ACTIONS: ${{ secrets.SIMDUTF_GH_ACTIONS }}
